### ISSUE TITLE
Distribute 0.6.16 is causing build failures

### ISSUE THREAD

**Issue by webmaven** [rodaebel/boboongae#2]
Distribute 0.6.16 was released today, and for some reason the bootstrap.py is trying to install it in the system python after it downloads and installs 0.6.15:

$ python2.5 bootstrap.py --distribute
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.15.tar.gz
Extracting in /tmp/tmpW9stnl
Now working in /tmp/tmpW9stnl/distribute-0.6.15
Building a Distribute egg in /tmp/tmprJtKKZ
/tmp/tmprJtKKZ/distribute-0.6.15-py2.5.egg
Creating directory '/home/webmaven/Desktop/projects/boboongae/bin'.
Creating directory '/home/webmaven/Desktop/projects/boboongae/parts'.
Creating directory '/home/webmaven/Desktop/projects/boboongae/eggs'.
Creating directory '/home/webmaven/Desktop/projects/boboongae/develop-eggs'.
Getting distribution for 'distribute'.
Before install bootstrap.
Scanning installed packages
No setuptools distribution found
After install bootstrap.
Creating /usr/lib/python2.5/site-packages/setuptools-0.6c11-py2.5.egg-info
error: /usr/lib/python2.5/site-packages/setuptools-0.6c11-py2.5.egg-info: Permission denied
An error occurred when trying to install distribute 0.6.16. Look above this message for any errors that were output by easy_install.
While:
  Bootstrapping.
  Getting distribution for 'distribute'.
Error: Couldn't install: distribute 0.6.16

**Comment by rodaebel** [comment]
Hi webmaven,

I suspect, the 0.6.16 release behaves somewhat odd when used with zc.buidlout. Does this patch https://gist.github.com/950632 work for you? It basically pins the distribute version to 0.6.15.

Cheers,
Tobias

**Comment by webmaven** [comment]
Yup, that works fine. The strange thing is that bootstrap.py specifies 0.6.15, so I am unsure why 0.6.16 was being installed at all, and even less sure why it was trying to install globally. Anyway, thanks for the solution!

**Comment by rodaebel** [comment]
I've addressed this on the distutils-sig mailing list. See http://mail.python.org/pipermail/distutils-sig/2011-May/017751.html for further details. Thanks to the amazingly quick response of Tarek Ziadé, this is fixed now for the world and pinning to 0.6.15 is not needed anymore.

**Comment by webmaven** [comment]
I still don't really understand why we got the errors we did.

It seems really odd that a failure to update the bootstrap.py script would result in an attempt by buildout to install a _later_ version of distribute. Further, it seems really odd that it would try to install it globally. Shouldn't it fail more gracefully (and I bet this will happen again with another release, eventually)?

**Comment by webmaven** [comment]
Hi there, I don't know whether this or any similar problems have come up in the last five years, but it is probably safe to close this issue. :smiling_imp:
